version: '3'
services:
  app:
    container_name: holiday
    image: magichousetop/holiday:2.0.0-docker
    ports:
      - "8001:8001"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
  db:
    container_name: db
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=magichouse-api
    volumes:
      - db_data:/var/lib/mysql
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db_data: